# Site settings
description: "한의원 블로그"
baseurl: "" # the subpath of your site, e.g. /blog
_url: "https://moonhani.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "http://127.0.0.1:4000"

# User settings
username: haniwon
user_description: 00한의원
user_title: 한의원
email: haniwon@hotmail.com
twitter_username: monwater
github_username:  moonhani
gplus_username:  lorem_ipsum
disqus_username: moonHani

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
